# Generated by Django 5.2.5 on 2026-03-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('products', '0002_link_posts_and_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_categories',
            field=models.ManyToManyField(blank=True, help_text='หมวดสินค้าที่เกี่ยวข้องกับบทความนี้', related_name='related_posts', to='products.category'),
        ),
    ]
