# Generated by Django 5.2.5 on 2026-03-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='line_contact_link',
            field=models.URLField(default='https://line.me/', help_text='ลิงก์สั่งซื้อผ่าน LINE', max_length=500),
        ),
    ]
