# Generated by Django 5.2.5 on 2026-03-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_link_posts_and_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='line_contact_link',
            field=models.URLField(default='https://line.me/R/ti/p/@Dr.peakmaker', help_text='ลิงก์สั่งซื้อผ่าน LINE (Dr.peakmaker)', max_length=500),
        ),
    ]
